//
// Generated file, do not edit! Created by nedtool 5.3 from src/messages/ContentResponse.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CONTENTRESPONSE_M_H
#define __CONTENTRESPONSE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0503
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "veins/modules/messages/WaveShortMessage_m.h"
// }}

/**
 * Class generated from <tt>src/messages/ContentResponse.msg:7</tt> by nedtool.
 * <pre>
 * packet ContentResponse extends WaveShortMessage
 * {
 *     string carId;
 *     int rsuId;
 * }
 * </pre>
 */
class ContentResponse : public ::WaveShortMessage
{
  protected:
    ::omnetpp::opp_string carId;
    int rsuId;

  private:
    void copy(const ContentResponse& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ContentResponse&);

  public:
    ContentResponse(const char *name=nullptr, short kind=0);
    ContentResponse(const ContentResponse& other);
    virtual ~ContentResponse();
    ContentResponse& operator=(const ContentResponse& other);
    virtual ContentResponse *dup() const override {return new ContentResponse(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getCarId() const;
    virtual void setCarId(const char * carId);
    virtual int getRsuId() const;
    virtual void setRsuId(int rsuId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ContentResponse& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ContentResponse& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CONTENTRESPONSE_M_H

