//
// Generated file, do not edit! Created by nedtool 5.1 from src/messages/RequestMessage.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __REQUESTMESSAGE_M_H
#define __REQUESTMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0501
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "veins/modules/messages/WaveShortMessage_m.h"
// }}

/**
 * Class generated from <tt>src/messages/RequestMessage.msg:7</tt> by nedtool.
 * <pre>
 * packet RequestMessage extends WaveShortMessage
 * {
 *     int requestedValue;
 * }
 * </pre>
 */
class RequestMessage : public ::WaveShortMessage
{
  protected:
    int requestedValue;

  private:
    void copy(const RequestMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RequestMessage&);

  public:
    RequestMessage(const char *name=nullptr, short kind=0);
    RequestMessage(const RequestMessage& other);
    virtual ~RequestMessage();
    RequestMessage& operator=(const RequestMessage& other);
    virtual RequestMessage *dup() const override {return new RequestMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getRequestedValue() const;
    virtual void setRequestedValue(int requestedValue);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RequestMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RequestMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __REQUESTMESSAGE_M_H

