//
// Generated file, do not edit! Created by nedtool 5.3 from src/RandomForestApp/RandomForestMessages/ConnectionConfirmation.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CONNECTIONCONFIRMATION_M_H
#define __CONNECTIONCONFIRMATION_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0503
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "veins/modules/messages/WaveShortMessage_m.h"
// }}

/**
 * Class generated from <tt>src/RandomForestApp/RandomForestMessages/ConnectionConfirmation.msg:7</tt> by nedtool.
 * <pre>
 * packet ConnectionConfirmation extends WaveShortMessage
 * {
 *     int virtualServerId;
 *     int loadBalancerId;
 *     int computationPower;
 * }
 * </pre>
 */
class ConnectionConfirmation : public ::WaveShortMessage
{
  protected:
    int virtualServerId;
    int loadBalancerId;
    int computationPower;

  private:
    void copy(const ConnectionConfirmation& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ConnectionConfirmation&);

  public:
    ConnectionConfirmation(const char *name=nullptr, short kind=0);
    ConnectionConfirmation(const ConnectionConfirmation& other);
    virtual ~ConnectionConfirmation();
    ConnectionConfirmation& operator=(const ConnectionConfirmation& other);
    virtual ConnectionConfirmation *dup() const override {return new ConnectionConfirmation(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getVirtualServerId() const;
    virtual void setVirtualServerId(int virtualServerId);
    virtual int getLoadBalancerId() const;
    virtual void setLoadBalancerId(int loadBalancerId);
    virtual int getComputationPower() const;
    virtual void setComputationPower(int computationPower);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ConnectionConfirmation& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ConnectionConfirmation& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CONNECTIONCONFIRMATION_M_H

