//
// Generated file, do not edit! Created by nedtool 5.3 from src/RandomForestApp/RandomForestMessages/ConnectionApproval.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CONNECTIONAPPROVAL_M_H
#define __CONNECTIONAPPROVAL_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0503
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "veins/modules/messages/WaveShortMessage_m.h"
// }}

/**
 * Class generated from <tt>src/RandomForestApp/RandomForestMessages/ConnectionApproval.msg:7</tt> by nedtool.
 * <pre>
 * packet ConnectionApproval extends WaveShortMessage
 * {
 *     int virtualServerId;
 *     int loadBalancerId;
 * }
 * </pre>
 */
class ConnectionApproval : public ::WaveShortMessage
{
  protected:
    int virtualServerId;
    int loadBalancerId;

  private:
    void copy(const ConnectionApproval& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ConnectionApproval&);

  public:
    ConnectionApproval(const char *name=nullptr, short kind=0);
    ConnectionApproval(const ConnectionApproval& other);
    virtual ~ConnectionApproval();
    ConnectionApproval& operator=(const ConnectionApproval& other);
    virtual ConnectionApproval *dup() const override {return new ConnectionApproval(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getVirtualServerId() const;
    virtual void setVirtualServerId(int virtualServerId);
    virtual int getLoadBalancerId() const;
    virtual void setLoadBalancerId(int loadBalancerId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ConnectionApproval& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ConnectionApproval& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CONNECTIONAPPROVAL_M_H

