//
// Generated file, do not edit! Created by nedtool 5.3 from src/RandomForestApp/RandomForestMessages/ConnectionRequest.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CONNECTIONREQUEST_M_H
#define __CONNECTIONREQUEST_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0503
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "veins/modules/messages/WaveShortMessage_m.h"
// }}

/**
 * Class generated from <tt>src/RandomForestApp/RandomForestMessages/ConnectionRequest.msg:7</tt> by nedtool.
 * <pre>
 * packet ConnectionRequest extends WaveShortMessage
 * {
 *     int virtualServerId;
 * }
 * </pre>
 */
class ConnectionRequest : public ::WaveShortMessage
{
  protected:
    int virtualServerId;

  private:
    void copy(const ConnectionRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ConnectionRequest&);

  public:
    ConnectionRequest(const char *name=nullptr, short kind=0);
    ConnectionRequest(const ConnectionRequest& other);
    virtual ~ConnectionRequest();
    ConnectionRequest& operator=(const ConnectionRequest& other);
    virtual ConnectionRequest *dup() const override {return new ConnectionRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getVirtualServerId() const;
    virtual void setVirtualServerId(int virtualServerId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ConnectionRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ConnectionRequest& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CONNECTIONREQUEST_M_H

