//
// Generated file, do not edit! Created by nedtool 5.1 from src/RandomForestApp/RandomForestMessages/TaskAlreadyFinished.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __TASKALREADYFINISHED_M_H
#define __TASKALREADYFINISHED_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0501
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "veins/modules/messages/WaveShortMessage_m.h"
// }}

/**
 * Class generated from <tt>src/RandomForestApp/RandomForestMessages/TaskAlreadyFinished.msg:7</tt> by nedtool.
 * <pre>
 * packet TaskAlreadyFinished extends WaveShortMessage
 * {
 *     int loadBalancerId;
 *     int taskId;
 * }
 * </pre>
 */
class TaskAlreadyFinished : public ::WaveShortMessage
{
  protected:
    int loadBalancerId;
    int taskId;

  private:
    void copy(const TaskAlreadyFinished& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TaskAlreadyFinished&);

  public:
    TaskAlreadyFinished(const char *name=nullptr, short kind=0);
    TaskAlreadyFinished(const TaskAlreadyFinished& other);
    virtual ~TaskAlreadyFinished();
    TaskAlreadyFinished& operator=(const TaskAlreadyFinished& other);
    virtual TaskAlreadyFinished *dup() const override {return new TaskAlreadyFinished(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getLoadBalancerId() const;
    virtual void setLoadBalancerId(int loadBalancerId);
    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskAlreadyFinished& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskAlreadyFinished& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TASKALREADYFINISHED_M_H

